### ISSUE TITLE
module 'os' has no attribute 'exists'

### ISSUE THREAD

**Issue by adammhaile** [timedata-org/loady#12]
I think this is caused by //git/ paths... doesn't really affect me at the moment, but should probably be fixed ASAP. Especially since you just need to use `os.path.exists`
```
bp run /home/adam/Stuff/dev/BP3/BiblioPixel/test/bibliopixel/project/simpixel_project.json --verbose
Traceback (most recent call last):
  File "/home/adam/Stuff/pyenv/bp3/bin/bp", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/adam/Stuff/dev/BP3/BiblioPixel/scripts/bp", line 15, in <module>
    main.main()
  File "/home/adam/Stuff/dev/BP3/BiblioPixel/bibliopixel/main/main.py", line 62, in main
    return run(args) or 0
  File "/home/adam/Stuff/dev/BP3/BiblioPixel/bibliopixel/main/run.py", line 17, in run
    animation = common_flags.make_animation(args, desc or {})
  File "/home/adam/Stuff/dev/BP3/BiblioPixel/bibliopixel/main/common_flags.py", line 130, in make_animation
    return project.project_to_animation(desc, project_flags)
  File "/home/adam/Stuff/dev/BP3/BiblioPixel/bibliopixel/project/project.py", line 87, in project_to_animation
    extend_path(path)
  File "/home/adam/Stuff/dev/BP3/BiblioPixel/bibliopixel/project/project.py", line 42, in extend_path
    loady.sys_path.extend(path)
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/sys_path.py", line 14, in extend
    sys.path.extend([library.to_path(p) for p in path])
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/sys_path.py", line 14, in <listcomp>
    sys.path.extend([library.to_path(p) for p in path])
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/library.py", line 75, in to_path
    library = create(gitpath)
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/library.py", line 71, in create
    return Library(*path.split('/'))
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/library.py", line 27, in __init__
    whitelist.check_entry(provider, user, project, branch, commit)
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/whitelist.py", line 66, in check_entry
    whitelist = read_whitelist()
  File "/home/adam/Stuff/pyenv/bp3/lib/python3.5/site-packages/loady/whitelist.py", line 18, in read_whitelist
    if os.exists(filename):
AttributeError: module 'os' has no attribute 'exists'
```

**Comment by rec** [comment]
Fixed, and released as 1.6.6.  Thanks for finding this dumb error.  :-)
